### ISSUE TITLE
progress cannot be retriggered once its done

### ISSUE THREAD

**Issue by liziqiang** [dominique-mueller/simple-progress-webpack-plugin#11]
Reset the `previousStep` to `0` will fix this.
![fix](https://cloud.githubusercontent.com/assets/208130/25690021/964e42dc-30bf-11e7-92c3-4db850b74252.jpg)
And also, total time shoud be updated.

**Comment by dominique-mueller** [comment]
What your situation exactly? Do you use this plugin in a watcher-like task, and it only shows the progress of the first build?

**Comment by liziqiang** [comment]
@dominique-mueller I'm using webpack to watch file changes. And it only shows the progress of the first build.

**Comment by dominique-mueller** [comment]
Once I find the time I'll fix it, resetting all values in the last step should hopefully fix it.

**Comment by dominique-mueller** [comment]
The fix is available with v1.0.4!
