### ISSUE TITLE
Issue with friendly-errors-webpack-plugin

### ISSUE THREAD

**Issue by IgnusG** [dominique-mueller/simple-progress-webpack-plugin#15]
If the code doesn't compile properly on initial run, friendly-errors should display an error message, but it doesn't if used together with this plugin.

It works as expected if the code compiles - you make changes - and then an error occurs.
It also works if I only use the friendly-errors plugin without this one.

It feels as if the plugin eats the error message.

Relevant lines
```javascript
  devServer: {
    quiet: true
  },
  plugins: [
    new SimpleProgressWebpackPlugin({
      format: 'compact'
    }),
    new FriendlyErrorsWebpackPlugin()
  ]
```

**Comment by dominique-mueller** [comment]
Do you have an example repository one could re-produce this issue? Plus, have you checked if the issue still exists when using Webpack 4?

**Comment by IgnusG** [comment]
I don’t even remember but feel free to close it. I don’t think I came across this issue anymore

**Comment by dominique-mueller** [comment]
Ok, then I'm closing this for now. If anyone experiences the issue described here, please add a comment and I will re-open.
