### ISSUE TITLE
Progress Title Possibilities 

### ISSUE THREAD

**Issue by tim-soft** [dominique-mueller/simple-progress-webpack-plugin#39]
Let's say my webpack config generates separate `client`, `server` and `socket` bundles.

Could it be feasible to pass a string into the plugin config to replace `Webpack: ...Starting` with whatever makes sense, such as `Building Socket Bundle...`

The feature would basically need to pass a variable to https://github.com/dominique-mueller/simple-progress-webpack-plugin/blob/156cbe8944080d2f54a86b63f78d5d53fb825997/logger/compact-logger.js#L43

**Comment by dominique-mueller** [comment]
Love the idea! Maybe as a `title` configuration option? Feel free to open a PR with this feature, if you want :)

**Comment by itsdevdom** [comment]
Closed by https://github.com/dominique-mueller/simple-progress-webpack-plugin/pull/62, the new option is called `name`.

**Comment by itsdevdom** [comment]
Released with **[2.0.0](https://github.com/dominique-mueller/simple-progress-webpack-plugin/releases/tag/2.0.0)**!
