### ISSUE TITLE
Import & Typescript support 

### ISSUE THREAD

**Issue by ietabhi** [dominique-mueller/simple-progress-webpack-plugin#44]
When i convert to typescript, below code not working:-

import * as SimpleProgressWebpackPlugin from "simple-progress-webpack-plugin"

plugins: [
  new SimpleProgressWebpackPlugin( { // Default options
    format: 'compact'
  } )
]

**Comment by dominique-mueller** [comment]
What exactly isn't working, do you see an error? Do you perhaps have a repro, e.g. a GitHub repository?

**Comment by ietabhi** [comment]
Getting error when compiling  : Only a void function can be called with the 'new' keyword

**Comment by itsdevdom** [comment]
Closed by #60.
