### ISSUE TITLE
"Normal" logging in CI environment

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [dominique-mueller/simple-progress-webpack-plugin#45]
Hey @dominique-mueller, this is more of a question / discussion.

Locally, the `minimal` and `compact` loggers are great.  In our CI environment, I switch to `expanded`.  This produces thousands of lines of logs (for our projects).

I'm wondering if we could introduce a logger that's good for the CI (one entry per line), but not quite as  lengthy as the `expanded` setting.  More like `compact`, but again, have each summary step on it's on line - maybe 10 - 20 lines total.

Thanks for your time!

**Comment by dominique-mueller** [comment]
While I'm not 100% sure about the name, I generally like the idea of having a less-verbose CI-ready logger. What are you thinking it should log? Same as `compact`, perhaps with the sub-messages for the optimization step?

**Comment by Blackbaud-BobbyEarl** [comment]
I think that would be fine.  I'm not sure about the name either.  Perhaps `compact-ci`?

**Comment by itsdevdom** [comment]
Closed by https://github.com/dominique-mueller/simple-progress-webpack-plugin/pull/63.

**Comment by itsdevdom** [comment]
Released with **[2.0.0](https://github.com/dominique-mueller/simple-progress-webpack-plugin/releases/tag/2.0.0)**!
