### ISSUE TITLE
Got Errors while using this plugin

### ISSUE THREAD

**Issue by liziqiang** [dominique-mueller/simple-progress-webpack-plugin#7]
![bug](https://cloud.githubusercontent.com/assets/208130/25607159/e4a4e0fe-2f47-11e7-87c1-c532d5190246.jpg)
see, variable `betterModuleName` can be `undefined`, and this cause errors when executing `betterModuleName.replace`.

**Comment by dominique-mueller** [comment]
Could you find out what the `moduleName` causing the error is? Maybe by adding a few `console.log()`s in the library code? This would really help identifying the actual issue. Also, what frontend technologies are you using (TypeScript, Angular, or similar)?

**Comment by liziqiang** [comment]
I'm using Vue 2.0. The code bellow might cause the error.
`betterModuleName.split( `${ absoluteProjectPath }\\` )[ 1 ]`

![log](https://cloud.githubusercontent.com/assets/208130/25620158/0bbec3ac-2f80-11e7-82aa-fa3d12233e52.jpg)

**Comment by dominique-mueller** [comment]
Ah, seems to be an issue with the backslash in the path; either we need to remove the backslash from the split argument (and then remove the first character from the result), or we need to normalize the path in some way.

I'll look into it as soon as I have the time :)

**Comment by dominique-mueller** [comment]
@liziqiang Opened a PR containing the (hopefully working) fix - could you be so kind copying the changes to your library code? It's just a few lines, and it's really hard to test if it got fixed from my side.

**Comment by liziqiang** [comment]
@dominique-mueller Good job! It works.

**Comment by dominique-mueller** [comment]
@liziqiang I love you man! Thanks for the effort, just released v1.0.3 which includes the fix!
